# Generated by Django 4.0.6 on 2022-07-20 13:37

from django.db import migrations, models
import product_scan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product_scan.models.upload_to, verbose_name='Image')),
            ],
        ),
    ]
